<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>SetlX</string>
    <key>scopeName</key>
    <string>source.stlx</string>
    <key>fileTypes</key>
    <array>
        <string>stlx</string>
    </array>
    <key>uuid</key>
    <string>7b37ebcb-f741-407e-be12-9ed789e7b373</string>
    <key>patterns</key>
    <array>
		<dict>
			<key>match</key>
			<string>\b(break|else|for|if|elseif|return|while|procedure|in)\b</string>
			<key>name</key>
			<string>keyword.control.lua</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bracketed_content</string>
		</dict>
    </array>
</dict>
</plist>